##' Age ranges for selection based on age.
##'
##' None
##' @title age_select 
##' @param ... Ignored
##' @return A list with variable names as the elements. Each element is itself a
##'     list with species as the elements. Each speices element is a list with
##'     the age range for a locale as the elements as a length 2 vector with the
##'     lower limit as the first value and the upper limit as the second value.
##' @author Erik Lampa
##' @examples age_select() ## Show the entire list
##'
##'     ## Create the age selection but change the lower limit for Hg of
##'     ## herrings at Landsort to 1.
##'     agesel <- age_select()
##'     agesel$HG$CLUP$LAND[1] <- 1
##' @export
##' 
age_select <- function(...) {
    ## Sets the age selection rules for the different variables, species and locales.
    list(KOND = list(CLUP = list(HAFJ = c(3, 5),
                                 ANGK = c(3, 6),
                                 LAND = c(3, 5),
                                 UTLA = c(2, 4),
                                 FLAD = c(2, 3),
                                 ANGV = c(2, 6),
                                 UTLV = c(2, 5)),
                     GADU = list(SEGO = c(2, 4),
                                 FLAD = c(2, 4)),
                     PERC = list(KVFJ = c(3, 4))),
         FPRC = list(CLUP = list(HAFJ = c(3, 5),
                                 ANGK = c(3, 6),
                                 LAND = c(3, 5),
                                 UTLA = c(2, 4),
                                 FLAD = c(2, 3),
                                 ANGV = c(2, 6),
                                 UTLV = c(2, 5)),
                     GADU = list(SEGO = c(2, 4),
                                 FLAD = c(2, 4)),
                     PERC = list(KVFJ = c(3, 4))),
         HG = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         PB = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         CD = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         NI = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         CR = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         CU = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         ZN = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         AS = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         AG = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         SE = list(CLUP = list(HAFJ = c(3, 5),
                               ANGK = c(3, 6),
                               LAND = c(3, 5),
                               UTLA = c(2, 4),
                               FLAD = c(2, 3)),
                   GADU = list(SEGO = c(2, 4),
                               FLAD = c(2, 4)),
                   PERC = list(KVFJ = c(3, 7),
                               HOLM = c(0, 7))),
         CB118 = list(CLUP = list(HAFJ = c(3, 5),
                                  ANGK = c(3, 6),
                                  LAND = c(3, 5),
                                  UTLA = c(3, 5),
                                  FLAD = c(2, 3),
                                  VADO = c(2, 9),
                                  ANGV = c(2, 9),
                                  UTLV = c(2, 9)),
                      GADU = list(SEGO = c(2, 4),
                                  FLAD = c(2, 3))),
         CB153 = list(CLUP = list(HAFJ = c(3, 5),
                                  ANGK = c(3, 6),
                                  LAND = c(3, 5),
                                  UTLA = c(3, 5),
                                  FLAD = c(2, 3),
                                  VADO = c(2, 9),
                                  ANGV = c(2, 9),
                                  UTLV = c(2, 9)),
                      GADU = list(SEGO = c(2, 4),
                                  FLAD = c(2, 3))),
         DDE = list(CLUP = list(HAFJ = c(3, 5),
                                ANGK = c(3, 6),
                                LAND = c(3, 5),
                                UTLA = c(3, 5),
                                FLAD = c(2, 3),
                                VADO = c(2, 3),
                                ANGV = c(2, 6),
                                UTLV = c(2, 4)),
                    GADU = list(SEGO = c(2, 4),
                                FLAD = c(2, 3)),
                    PERC = list(KVFJ = c(3, 4))),
         AHCH = list(CLUP = list(HAFJ = c(3, 5),
                                 ANGK = c(3, 6),
                                 LAND = c(3, 5),
                                 UTLA = c(3, 5),
                                 FLAD = c(2, 3),
                                 ANGV = c(2, 6),
                                 UTLV = c(2, 5)),
                     GADU = list(FLAD = c(2, 3))),
         LINDA = list(CLUP = list(HAFJ = c(3, 5),
                                  ANGK = c(3, 6),
                                  LAND = c(3, 5),
                                  UTLA = c(3, 5),
                                  FLAD = c(2, 3),
                                  ANGV = c(2, 6),
                                  UTLV = c(2, 5)),
                      GADU = list(SEGO = c(2, 4),
                             FLAD = c(2, 3))),
         HCB = list(CLUP = list(HAFJ = c(3, 5),
                                ANGK = c(3, 6),
                                LAND = c(3, 5),
                                UTLA = c(3, 5),
                                FLAD = c(2, 3),
                                ANGV = c(2, 6),
                                UTLV = c(2, 5)),
                    GADU = list(SEGO = c(2, 4),
                                FLAD = c(2, 3)))
         )
}
